package common;

import java.io.Serializable;

/**
 * A serializable definition of ChatRoom.
 */
public class ChatRoom implements Serializable {
	private static final long serialVersionUID = 1L;

	public int cid;

	// Type of the ChatRoom
	// 0 - Private Chat
	// 1 - Group Chat
	public int type;

	// Group number (if it is a group ChatRoom, or null)
	public Integer groupNumber;

	// ChatRoom title (may be generated by the server)
	public String title;

	// Messages in this chatroom
	public String messages;

	// Unread messages count
	public int unreadCount;

	public ChatRoom(int cid, int type, Integer groupNumber) {
		this.cid = cid;
		this.type = type;
		this.groupNumber = groupNumber;
		messages = "";
		title = "";
		unreadCount = 0;
	}

	public void addMessage(ChatMessage message) {
		messages += message.displayMessage();
		++unreadCount;
	}

	/**
	 * Get the title of this ChatRoom
	 */
	@Override
	public String toString() {
		String title = this.title;
		if (unreadCount > 0)
			title += String.format(" (%d)", unreadCount);
		return title;
	}
}
